# Generated by Django 2.0.4 on 2018-04-19 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20180419_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.CharField(default=11, max_length=32),
            preserve_default=False,
        ),
    ]
